/** Declaration file generated by dts-gen */

export = ml_svm;

declare class ml_svm {
  constructor(options: any);

  margin(features: any): any;

  marginOne(features: any, noWhitening: any): any;

  predict(features: any): any;

  predictOne(p: any): any;

  supportVectors(): any;

  toJSON(): any;

  train(features: any, labels: any): void;

  static load(model: any): any;
}
